# Generated by Django 2.2.16 on 2022-01-16 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220115_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default=1, verbose_name='Биография'),
            preserve_default=False,
        ),
    ]
