# Generated by Django 2.2.16 on 2022-01-19 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_extendeduser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtendedUser',
        ),
    ]
