# Generated by Django 2.2.16 on 2022-01-11 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ('name', 'category'), 'verbose_name': 'произведение', 'verbose_name_plural': 'произведения'},
        ),
        migrations.RemoveField(
            model_name='title',
            name='pub_date',
        ),
    ]
