# Generated by Django 2.2.16 on 2022-01-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, default=5, verbose_name='описание'),
            preserve_default=False,
        ),
    ]
